b=float(input("Enter value:"))
h=float(input("Enter value:"))
l=float(input("Enter value:"))
b1=float(input("Enter value:"))
s=float(input("Enter value:"))
print("area of traingle:"+ 0.5*b*h)
print("Area of rectangle:"+l*b)
print("area of square:"+s*s)